### ISSUE TITLE
imx-bootlets doesn't build if compiler has SSP enabled

### ISSUE THREAD

**Issue by sjlongland** [embeddedarm/linux-2.6.35.3-imx28#1]
I used Gentoo Crossdev to generate a toolchain for compiling to arm-linux as the Technologix one is compiled for i386 and my host runs AMD64 Linux.

This works for building the kernel and userspace programs, and I already use the same toolchain for developing software for another ARM system.  However, it fails when building the `imx-bootlets` with the following error:

```
arm-unknown-linux-gnueabi-cpp -P -DBASE_ADDR=0x00002000 -o output-target/linux_prep.ld linux_prep.ld.in
arm-unknown-linux-gnueabi-ld -o output-target/linux_prep ./core/entry.o ./core/resume.o ./core/cmdlines.o ./core/setup.o ./core/keys.o ./board/iMX28_EVK.o ./hw/lradc-buttons.o -static -nostdlib -T ./output-target/linux_prep.ld -L/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.3/ -lgcc
./board/iMX28_EVK.o: In function `get_board_rev':
iMX28_EVK.c:(.text+0x3c): undefined reference to `__stack_chk_fail'
iMX28_EVK.c:(.text+0x50): undefined reference to `__stack_chk_guard'
make[1]: *** [output-target/linux_prep] Error 1
make[1]: Leaving directory `/home/stuartl/vrt/projects/arm/linux-2.6.35.3-imx28/imx-bootlets-src-10.12.01/linux_prep'
make: *** [linux_prep] Error 2
stuartl@rikishi ~/vrt/projects/arm/linux-2.6.35.3-imx28/imx-bootlets-src-10.12.01 $ ls boot_prep/
```

This is due to the C compiler emitting stack protection code, but the linker being told to skip `libssp`.  The stack protection is disabled by passing `-fno-stack-protector` when building binaries with `gcc`.  Attached is a patch that edits the necessary Makefiles within the `imx-bootlets` subtree to allow this to happen.  On compilers that default to `-fno-stack-protector` (such as the Technologix-supplied one) this should have no effect.

**Comment by sjlongland** [comment]
I couldn't figure out how to attach a patch.  Here's hoping github doesn't botch it too badly.

https://gist.github.com/sjlongland/1a3876b6422b813a51de#file-0001-imx-bootlets-add-fno-stack-protector-patch

**Comment by ts-kris** [comment]
We appreciate the information you have gathered and the patch you have supplied.  However, this is not an issue with our supplied tools, and our compiler does not generate this error on a 32 or 64 bit linux machine.  We try to limit our support to the tools we supply as the world of open-source things are rapidly changing and we strive to provide consistency and longevity in our products and tools.

This is good information to know and we will keep a note of it for future reference.
