### ISSUE TITLE
No PHY on first boot after power on.

### ISSUE THREAD

**Issue by ganehag** [embeddedarm/linux-2.6.35.3-imx28#2]
When doing a straight forward compile from the master branch and booting a TS7600 from the image. I always get this on the boot after power on.

> [    3.980000] eth0: no PHY found

After a reboot/reset (with power still on) I get this:

> [    4.000000] eth0: Freescale FEC PHY driver [Generic PHY](mii_bus:phy_addr=0:00, irq=-1)

Then after a hard reset (power cycle) it returns to the first state.

> [    3.970000] eth0: no PHY found

**Comment by ts-kris** [comment]
Confirmed.  We are looking in to this.

**Comment by ts-kris** [comment]
This has been fixed in commit 12538359937aeb7882f022c2af32f1868fc9a5b2

Please verify that it resolves your issue
